name: Verify shell scripts

on:
  push:
    branches:
      - master
    paths:
      - '**.sh'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        run: find . -type f -name "*.sh" -exec sh -c 'for file do echo "Checking: $file"; shellcheck -x -e SC2086,SC2181 "$file"; done' sh {} +
